<?php

return [
	'greetings' => [
		'You look especially amazing today.',
		"Hey, handsome!",
		"What's cookin good lookin!",
		"Have a great day!",
		"At the hairdressers, people just point at you and say 'like that'.", 
		"People talk about how nice you are behind your back.", 
		"In a fight, you could beat two sharks, a bear and five ducks." ,
		"You're the hero Gotham needs.",
		"You're classier than Sir Patrick Stewart playing a grand piano on a yacht in Monaco.",
		"You're in my top 5 humans of all time.",
		"If you tried, you could probably be quite famous.",
		"I'd clean the hair out of the plughole for you if I could. But I'm just a mirror.",
		"If you were a dinosaur you'd be a Legendasaurus Rex.",
		"You're a chocolate Hobnob in a jar of Rich Teas.",
		"If you were bacteria, you'd be the good kind.",
		"I'd be scared to play you at Scrabble.",
		"You're a glass of water after a long run.",
		"Is it a bird? Is it a plane? No. It's you, you massive legend.",
		"I admit it. You're funnier than me.",
		"Thanks for stepping into conversations when I say something awkward.",
		"You are a terrible cook. But a brilliant human.",
		"I once looked at your bum. I regret nothing.",
		"You're a Michelin Star human.",
		"You're smoother than Barry White in silk pyjamas operating a floor buffer.",
		"When my life flashes before my eyes, I hope it's mostly you.",
		"Stop. Looking. So. Good. People are trying to get on with their lives around here.",
		"You've really nailed being a human. Good job.",
		"You're the first person I'd look for after an apocalyptic event.",
		"You are more adorable than a baby panda riding a sneezing piglet.",
		"You're like a match. Small and fiery.",
		"You're the bee's knees, the cat's pyjamas, the pheasant's bowtie.",
		"Things I wish I could be: Ninja. Astronaut. You.",
		"You have the best dance moves. They're both great.",
		"Without you the world would have fewer people in it.",
		"Your hair is sleek and glossy like the mane of a mighty stallion.",
		"Your Twitter feed could win the Booker Prize.",
		"You're more supportive than a sports bra.",
		"You're my favourite person to be hungover with.",
		"Parkinson called. He wants his chat back.",
		"You always get the most pub quiz answers right.",
		"You're the hero Bonnie Tyler needed.",
		"If I had my way, they’d put a blue plaque up everywhere you went.",
		"8 out of 10 cats prefer you.",
		"You are a walking high-five.",
		"You could be a part-time model.",
		"I want to build a nest in your beard.",
		"I'd follow you into battle. Or to the shops. Or just on Twitter. Up to you.",
		"You're cooler than the other side of the pillow.",
		"You are tall. I like it.",
		"I love you more than tea.",
		"You’re a lot more intelligent than you look.",
		"I like your face.",
		"You're better than free wifi.",
		"You're wise and all knowing, like a mighty owl. But you're still always late.",
		"You’re the human equivalent of a bank holiday.",
		"You’re better than a perfectly ripe avocado.",
		"You are wonderfully odd.",
		"The best things come in tall packages.",
		"If we were marooned on an island, I'd be very sad when I had to eat you.",
	]
];